version: '3.3'
services:
  zookeeper:
    container_name: zookeeper_container
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - networkMovieFinder
  kafka:
    container_name: kafka_container
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CREATE_TOPICS: "orders"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    networks:
      - networkMovieFinder
  db_movies:
    container_name: movies_db
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movies
    ports:
      - "3306:3306"
    networks:
      - networkMovieFinder
  db_Users:
    container_name: users_db
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: users
    ports:
      - "3307:3306"
    networks:
      - networkMovieFinder
  eureka_server:
    container_name: eureka_server
    build:
      context: eureka
      dockerfile: Dockerfile
    image: eureka_server
    ports:
        - "8080:8080"
    networks:
      - networkMovieFinder
  front_micro:
    container_name: front_micro
    build:
      context: front
      dockerfile: Dockerfile
    image: front_micro
    ports:
      - "8082:8082"
    depends_on:
      - kafka
      - db_movies
      - db_Users
    networks:
      - networkMovieFinder
  back_micro:
    container_name: back_micro
    build:
      context: back
      dockerfile: Dockerfile
    image: back_micro
    ports:
      - "8081:8081"
    depends_on:
      - kafka
      - db_movies
      - db_Users
    networks:
      - networkMovieFinder
networks:
  networkMovieFinder:
    driver: "bridge"