version: '2'
services:
  zookeeper:
    container_name: zookeeper_container
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    container_name: kafka_container
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CREATE_TOPICS: "orders"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  db_movies:
    container_name: movies_db
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movies
    ports:
      - "3306:3306"
  db_Users:
    container_name: users_db
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: users
    ports:
      - "3307:3306"
  eureka_server:
    container_name: eureka_server
    build:
      context: eureka
      dockerfile: Dockerfile
    image: eureka_server
    ports:
        - "8080:8080"
  front_micro:
    container_name: front_micro
    build:
      context: front
      dockerfile: Dockerfile
    image: front_micro
    ports:
      - "8082:8082"
  back_micro:
    container_name: back_micro
    build:
      context: back
      dockerfile: Dockerfile
    image: back_micro
    ports:
      - "8081:8081"